name: Package TS Mod

on:
  push:
    paths:
      - 'TSTweaks/**'
      - '.github/workflows/package.yml'
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/TSTweaks
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm i
    - run: npm run buildinfo
    - run: |
        rm ./dist/*.zip
        echo "VERSION=$( npm pkg get version | sed 's/["]//g')" >> "$GITHUB_OUTPUT"
        echo "AKIVERSION=$( npm pkg get akiVersion | sed 's/["]//g')" >> "$GITHUB_OUTPUT"
        echo "COMMIT=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT" 
      id: version
    - uses: actions/upload-artifact@v4
      with:
        name: SPT-Tweaks-${{ steps.version.outputs.VERSION }}-${{ steps.version.outputs.COMMIT }}-AKI${{ steps.version.outputs.AKIVERSION }}
        path: ${{ github.workspace }}/TSTweaks/dist/**
        if-no-files-found: error
        compression-level: 9
